/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Thongke;

/**
 *
 * @author Admin
 */
public class JpThongKe extends javax.swing.JPanel {

    /**
     * Creates new form JpQuanLy
     */
    public JpThongKe() {
        initComponents();
        LoadPanel(1);
    }
    JpThongKeLuong luong;
    JpThongKeHoaDon hd;


    public void LoadPanel(int i) {
        JpQuanLy.removeAll();
        switch (i) {
            case 1:
                hd = new JpThongKeHoaDon();
                JpQuanLy.add(hd);
                break;
            case 2:
                luong = new JpThongKeLuong();
                JpQuanLy.add(luong);
                break;
            default:
                break;
        }
        JpQuanLy.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnThongKeHD = new javax.swing.JButton();
        btnThongKeLuong = new javax.swing.JButton();
        JpQuanLy = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(1051, 486));

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnThongKeHD.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnThongKeHD.setForeground(new java.awt.Color(51, 51, 0));
        btnThongKeHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/qluser.png"))); // NOI18N
        btnThongKeHD.setText("THỐNG KÊ HOÁ ĐƠN");
        btnThongKeHD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThongKeHD.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnThongKeHD.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThongKeHD.setIconTextGap(10);
        btnThongKeHD.setPreferredSize(new java.awt.Dimension(0, 35));
        btnThongKeHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeHDActionPerformed(evt);
            }
        });

        btnThongKeLuong.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnThongKeLuong.setForeground(new java.awt.Color(51, 51, 0));
        btnThongKeLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/qluser.png"))); // NOI18N
        btnThongKeLuong.setText("THỐNG KÊ LƯƠNG ");
        btnThongKeLuong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThongKeLuong.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnThongKeLuong.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThongKeLuong.setIconTextGap(10);
        btnThongKeLuong.setPreferredSize(new java.awt.Dimension(0, 35));
        btnThongKeLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeLuongActionPerformed(evt);
            }
        });

        JpQuanLy.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThongKeHD, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(btnThongKeLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 1026, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThongKeHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThongKeLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(JpQuanLy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThongKeHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeHDActionPerformed
        LoadPanel(1);  // TODO add your handling code here:
    }//GEN-LAST:event_btnThongKeHDActionPerformed

    private void btnThongKeLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeLuongActionPerformed
        // TODO add your handling code here:
        LoadPanel(2);
    }//GEN-LAST:event_btnThongKeLuongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpQuanLy;
    private javax.swing.JButton btnThongKeHD;
    private javax.swing.JButton btnThongKeLuong;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
