/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.BanHang;

import CustomTable.TableGoiMon;
import Models.LoaiMonAnDTO;
import Models.MonAnDTO;
import SQLConnect.ConnectSQL;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import java.sql.Timestamp;

/**
 *
 * @author ThangIKCU
 */
public class JpDoAn extends javax.swing.JPanel {

    ConnectSQL con = new ConnectSQL();
    /**
     * Creates new form jpThucDon
     */
    public Timestamp gioden;
    public String tenban;
    public int maban;

    ArrayList<MonAnDTO> arrThucDon;
    NumberFormat chuyentien = new DecimalFormat("#,###,###");
    public static JpDoAn td = new JpDoAn();

    public void FillLoai() {
        ArrayList<LoaiMonAnDTO> arrLoai = con.GetAllLoaiMonAn();
        if (arrLoai != null) {
            JButton btn;
            jpLoai.setLayout(new BoxLayout(jpLoai, BoxLayout.PAGE_AXIS));
            jpLoai.removeAll();
            jScrollPane2.getVerticalScrollBar().setUnitIncrement(15);
            for (LoaiMonAnDTO loai : arrLoai) {
                
                //btnDanhMucMonAn
                btn = new JButton(loai.getTenLoai());
                btn.setName(Integer.toString(loai.getMaLoai()));
                btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
                btn.setMaximumSize(new Dimension(120, 40));
                btn.setForeground(Color.decode("#331a00"));
                btn.setBorder(BorderFactory.createLineBorder(Color.WHITE, 2));
                btn.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mousePressed(MouseEvent e) {
                        lbNhom.setText("Nhóm " + loai.getTenLoai());
                        arrThucDon = con.GetAllMon(Integer.toString(loai.getMaLoai()));
            
                        if (arrThucDon != null) {
                            jTableChonMon.setModel(new TableGoiMon(arrThucDon));
                        }
                    }
                });
                jpLoai.add(btn);
                jpLoai.updateUI();
            }
        }
    }

    public JpDoAn() {
        initComponents();
        td = this;
        FillLoai();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbNhom = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jpChonMon = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableChonMon = new javax.swing.JTable();
        jpLoai = new javax.swing.JPanel();

        setBackground(Color.decode("#e6e6e6"));

        jPanel1.setBackground(Color.decode("#e6e6e6"));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNhom.setBackground(new java.awt.Color(11, 112, 14));
        lbNhom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbNhom.setForeground(new java.awt.Color(253, 253, 253));
        lbNhom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNhom.setText("                          Chọn món");
        lbNhom.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbNhom.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lbNhom.setIconTextGap(7);
        lbNhom.setOpaque(true);
        jPanel1.add(lbNhom, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 301, 36));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setAutoscrolls(true);

        jpChonMon.setLayout(new java.awt.GridLayout(0, 2, 5, 5));

        jTableChonMon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Món"
            }
        ));
        jTableChonMon.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableChonMon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableChonMonMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableChonMon);

        jpChonMon.add(jScrollPane1);

        jScrollPane2.setViewportView(jpChonMon);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 480));

        jpLoai.setBackground(Color.decode("#e6e6e6"));
        jpLoai.setLayout(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableChonMonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableChonMonMousePressed
        // TODO add your handling code here:
        jpChonMon.updateUI();
        DLSoLuong sl = new DLSoLuong(arrThucDon.get(jTableChonMon.getSelectedRow()).getMaMon(), tenban, maban);
        sl.gioden = gioden;
        sl.setVisible(true);
    }//GEN-LAST:event_jTableChonMonMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableChonMon;
    private javax.swing.JPanel jpChonMon;
    private javax.swing.JPanel jpLoai;
    private javax.swing.JLabel lbNhom;
    // End of variables declaration//GEN-END:variables

}
