/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.BanHang;

import Models.BanDTO;
import Models.DsOrder;
import Models.HoaDonDTO;
import Models.MonAnDTO;
import SQLConnect.ConnectSQL;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.Timestamp;

public final class JpGoiDo extends javax.swing.JPanel {

    public Timestamp gioden = new Timestamp(System.currentTimeMillis());// get datetime.now
    public String TenBan;
    int MaBan;
    int MaHD, Tienmon = 0, Tongtien = 0;
    ConnectSQL con = new ConnectSQL();
    HoaDonDTO arrHoaDon;
    NumberFormat Cash = new DecimalFormat("#,###,###");
    ArrayList<DsOrder> Orders;

    public static JpGoiDo Goimon;
    SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm a");

    /**
     * Creates new form JpGoiDo
     *
     * @param trangthai
     * @param tenban
     * @param maban
     */
    public JpGoiDo(String trangthai, String tenban, int maban) {
        initComponents();
        Goimon = this;
        MaBan = maban;
        TenBan = tenban;

        jpDsMon.setVisible(false);
        jpThongTinThanhToan.setVisible(false);
        jScrollPane1.setVisible(false);
        
        arrHoaDon = con.GetHDbyMaBan(maban);
        //Nếu có hoá đơn thì get chi tiết hoá đơn để gọi món
        if (arrHoaDon != null) {
            Orders = con.GetDsOrder(arrHoaDon.getMaHoaDon());
            fillDsMon(0);
            MaHD = arrHoaDon.getMaHoaDon();
            lbGioDen.setText(arrHoaDon.getGioDen());
        }
        lbTenBan.setText(tenban);
        lbTrangThai.setText(trangthai);

        if (lbTrangThai.getText().equals("Trống")) {
            return;      
        }
        
        // Add nhiều món vào hoá đơn thông qua trạng thái
        else if (lbTrangThai.getText().equals("Đang phục vụ")) {
            btnThuGon.setVisible(false);
            JpDoAn food = new JpDoAn();
            food.tenban = TenBan;
            food.maban = MaBan;
            jpThucDon.removeAll();
            jpThucDon.add(food);
            jpThucDon.updateUI();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jpThongTinBan = new javax.swing.JPanel();
        lbTenBan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbGioDen = new javax.swing.JLabel();
        lbTrangThai = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnGoiMon = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jpThongTinThanhToan = new javax.swing.JPanel();
        lbTongTien = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnThuGon = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jpDsMon = new javax.swing.JPanel();
        jpThucDon = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 0));
        jLabel5.setText("Thời gian phục vụ gần nhất");

        setBackground(Color.decode("#e6e6e6"));

        jpThongTinBan.setBackground(Color.decode("#e6e6e6"));
        jpThongTinBan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpThongTinBan.setAutoscrolls(true);

        lbTenBan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbTenBan.setText("Bàn 1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Giờ đến:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Trạng thái");

        lbGioDen.setText(".....");

        lbTrangThai.setText("....");

        jPanel1.setBackground(Color.decode("#e6e6e6"));

        btnGoiMon.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        btnGoiMon.setText("Gọi món");
        btnGoiMon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoiMon.setPreferredSize(new java.awt.Dimension(100, 40));
        btnGoiMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoiMonActionPerformed(evt);
            }
        });
        jPanel1.add(btnGoiMon);

        jSeparator1.setBackground(Color.decode("#e6e6e6"));
        jSeparator1.setForeground(new java.awt.Color(21, 75, 158));

        jpThongTinThanhToan.setBackground(Color.decode("#e6e6e6"));
        jpThongTinThanhToan.setAutoscrolls(true);
        jpThongTinThanhToan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbTongTien.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbTongTien.setForeground(new java.awt.Color(255, 0, 0));
        lbTongTien.setText("0");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("THÀNH TIỀN:");

        javax.swing.GroupLayout jpThongTinThanhToanLayout = new javax.swing.GroupLayout(jpThongTinThanhToan);
        jpThongTinThanhToan.setLayout(jpThongTinThanhToanLayout);
        jpThongTinThanhToanLayout.setHorizontalGroup(
            jpThongTinThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpThongTinThanhToanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(lbTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpThongTinThanhToanLayout.setVerticalGroup(
            jpThongTinThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpThongTinThanhToanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpThongTinThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbTongTien)))
        );

        btnThuGon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThuGon.setForeground(new java.awt.Color(0, 51, 51));
        btnThuGon.setText("<<");
        btnThuGon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuGonActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(Color.decode("#e6e6e6"));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jpDsMon.setBackground(Color.decode("#e6e6e6"));
        jpDsMon.setMaximumSize(new java.awt.Dimension(32767, 400));
        jpDsMon.setOpaque(false);

        javax.swing.GroupLayout jpDsMonLayout = new javax.swing.GroupLayout(jpDsMon);
        jpDsMon.setLayout(jpDsMonLayout);
        jpDsMonLayout.setHorizontalGroup(
            jpDsMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );
        jpDsMonLayout.setVerticalGroup(
            jpDsMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jpDsMon);

        javax.swing.GroupLayout jpThongTinBanLayout = new javax.swing.GroupLayout(jpThongTinBan);
        jpThongTinBan.setLayout(jpThongTinBanLayout);
        jpThongTinBanLayout.setHorizontalGroup(
            jpThongTinBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpThongTinBanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jpThongTinBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpThongTinBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpThongTinBanLayout.createSequentialGroup()
                        .addComponent(lbGioDen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(227, 227, 227))
                    .addGroup(jpThongTinBanLayout.createSequentialGroup()
                        .addComponent(lbTrangThai)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jpThongTinBanLayout.createSequentialGroup()
                .addGroup(jpThongTinBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThuGon)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpThongTinBanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpThongTinBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTenBan)
                            .addComponent(jpThongTinThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpThongTinBanLayout.createSequentialGroup()
                .addGroup(jpThongTinBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpThongTinBanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpThongTinBanLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpThongTinBanLayout.setVerticalGroup(
            jpThongTinBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpThongTinBanLayout.createSequentialGroup()
                .addComponent(btnThuGon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbTenBan)
                .addGap(27, 27, 27)
                .addGroup(jpThongTinBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbGioDen))
                .addGap(18, 18, 18)
                .addGroup(jpThongTinBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbTrangThai))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jpThongTinThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpThucDon.setBackground(Color.decode("#e6e6e6"));
        jpThucDon.setAutoscrolls(true);
        jpThucDon.setLayout(new java.awt.BorderLayout());

        jLabel1.setMaximumSize(new java.awt.Dimension(1258, 519));
        jLabel1.setMinimumSize(new java.awt.Dimension(1258, 519));
        jLabel1.setPreferredSize(new java.awt.Dimension(410, 470));
        jpThucDon.add(jLabel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpThongTinBan, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpThucDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpThucDon, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
            .addComponent(jpThongTinBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents
    public void fillThongTin() {
        arrHoaDon = con.GetHDbyMaBan(MaBan);
        MaHD = arrHoaDon.getMaHoaDon();
        btnGoiMon.setVisible(true);

        if (Tienmon <= 0) {
            Tongtien = 0;
            lbTongTien.setText("0 VNĐ");
        } else {
            Tongtien = Tienmon;
            lbTongTien.setText(String.valueOf(Cash.format(Tongtien)) + " VNĐ");
        }         
    }

    public void fillDsMon(int mahd) {
        //Hiển thị hoá đơn sau khi chọn món lên màn hình
        if (mahd != 0) {
            Orders = con.GetDsOrder(mahd);// get all thông tin từ bảng món và bảng chi tiết hoá đơn
            arrHoaDon = con.GetHDbyMaBan(MaBan);// lấy tất cả những hoá đơn đã có mã bàn và trạng thái = 0 
            Tienmon = 0;
        }
        mahd = MaHD;
        if (Orders != null) {
            jpDsMon.setVisible(true);
            jpThongTinThanhToan.setVisible(true);
            jScrollPane1.setVisible(true);
            btnGoiMon.setText("Thanh toán");
            JPanel[] pn = new JPanel[Orders.size()];
            jpDsMon.removeAll();
            jpDsMon.setLayout(new BoxLayout(jpDsMon, BoxLayout.Y_AXIS));
            for (int i = 0; i < Orders.size(); i++) {
                Tienmon += Orders.get(i).getDonGia()* Orders.get(i).getSoLuong();
                
                //panel chi tiết món
                pn[i] = new JPanel();
                pn[i].setName(Integer.toString(Orders.get(i).getMaMon()));
                pn[i].setCursor(new Cursor(Cursor.HAND_CURSOR));
                pn[i].setBorder(BorderFactory.createLineBorder(Color.darkGray, 1));
                pn[i].setBackground(Color.decode("#b3ff99"));
                pn[i].setLayout(new GridLayout());
                pn[i].setPreferredSize(new Dimension(270, 50));
                pn[i].setMaximumSize(new Dimension(270, 50));
                pn[i].setMinimumSize(new Dimension(270, 50));
                
                //Fill thong tin món
                pn[i].add(new JLabel(Orders.get(i).getTenMon(), JLabel.CENTER)).setForeground(Color.decode("#001a66"));
                pn[i].add(new JLabel(String.valueOf(Cash.format(Orders.get(i).getDonGia())) + " VNĐ", JLabel.CENTER)).setForeground(Color.decode("#ff0000"));
                pn[i].add(new JLabel(String.valueOf(Orders.get(i).getSoLuong()) + " " + Orders.get(i).getdVT(), JLabel.RIGHT)).setForeground(Color.decode("#008000"));
                
                //btn Huỷ
                Icon ic = new ImageIcon("C:\\Users\\Admin\\Desktop\\BTL_Nhom4\\src\\Interface\\Images\\tru(-).png");
                JLabel lbl = new JLabel("", ic, JLabel.CENTER);
                lbl.setForeground(Color.decode("#b3ff99"));
                lbl.setName(Integer.toString(Orders.get(i).getMaMon()));
                pn[i].add(lbl).addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        int cancel;
                        ArrayList<MonAnDTO> td = con.GetMonAnById(Integer.parseInt(e.getComponent().getName()));
                        ///Huỷ món panel
                        cancel = JOptionPane.showConfirmDialog(null, "Hủy món: " + td.get(0).getTenMon() + " ?", "Hủy món", JOptionPane.YES_NO_OPTION);

                        if (cancel == JOptionPane.YES_OPTION) {
                            int xoa = con.DeleteMonFromCTHD(Integer.parseInt(e.getComponent().getName()), MaHD, MaBan);
                            
                            if (xoa == 1) {
                                fillDsMon(MaHD);
                            }
                            //Nếu xoá hết thì huỷ bàn
                            if (xoa == 2) {
                                fillDsMon(MaHD);
                                HuyHD();
                            }
                        }
                    }
                });
                pn[i].addMouseListener(new MouseAdapter() {
                    @Override
                    public void mousePressed(MouseEvent e) {
                        DLSoLuong sl = new DLSoLuong(Integer.parseInt(e.getComponent().getName()), TenBan, MaBan);
                        sl.setVisible(true);
                    }
                });
                jpDsMon.add(pn[i]); 
                jpDsMon.updateUI();

            }
            fillThongTin();
        }
    }
    //Btn Huỷ bàn
    private void HuyHD() {
        JButton btnhuy = new JButton("Hủy bàn");
        btnhuy.setPreferredSize(new Dimension(100, 40));
        btnhuy.setBounds(100, 50, 100, 40);
        jpDsMon.setLayout(null);
        btnGoiMon.setVisible(false);
        jpThongTinThanhToan.setVisible(false);
        btnhuy.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                BanDTO b = new BanDTO();
                b.SetTrangThai("Trống");
                b.SetMaBan(MaBan);
                con.UpDateTrangThaiBan(b);

                JpBanDoAn.bh.FillBan();
                JpGoiDo.Goimon.removeAll();
                JpBanDoAn.bh.ThuGon();

                HoaDonDTO hd = new HoaDonDTO();
                hd.setMaHoaDon(MaHD);
                con.HuyHD(hd);
            }
        });
        jpDsMon.add(btnhuy);
        jpDsMon.updateUI();
    }
    private void btnGoiMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoiMonActionPerformed
        if (btnGoiMon.getText().equals("Hủy bàn")) {
            jpThucDon.removeAll();
            jpThucDon.updateUI();
            jpThongTinThanhToan.setVisible(false);
            btnThuGon.setVisible(true);
            lbGioDen.setText("......");
            lbTrangThai.setText("Trống");
            String TrangThai = "Trống";
            
            BanDTO b = new BanDTO(MaBan, lbTenBan.getText(), TrangThai);
            int Update = con.UpdateBan(b);
            JpBanDoAn.bh.FillBan();
            btnGoiMon.setText("Gọi món");
            return;

        }
        if (btnGoiMon.getText().equals("Thanh toán")) {
            DLThanhToan thanhtoan = new DLThanhToan(Tongtien, TenBan, MaBan, MaHD);
            thanhtoan.setLocationRelativeTo(null);
            thanhtoan.setVisible(true);
            return;
        }
        
        if (btnGoiMon.getText().equals("Gọi món")) {
            jpThucDon.setVisible(true);
            Timestamp date = new Timestamp(System.currentTimeMillis());
            SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm a");
            SimpleDateFormat sf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            lbGioDen.setText(df.format(date));
            lbTrangThai.setText("Đang phục vụ");
  
            btnThuGon.setVisible(false);
            btnGoiMon.setText("Hủy bàn");

            JpDoAn thucdon;
            thucdon = new JpDoAn();
            thucdon.maban = MaBan;
            thucdon.tenban = TenBan;

            thucdon.gioden = date;
            jpThucDon.removeAll();
            jpThucDon.add(thucdon);
            jpThucDon.revalidate();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoiMonActionPerformed

    private void btnThuGonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuGonActionPerformed
        JpBanDoAn.bh.ThuGon();
    }//GEN-LAST:event_btnThuGonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoiMon;
    private javax.swing.JButton btnThuGon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jpDsMon;
    private javax.swing.JPanel jpThongTinBan;
    private javax.swing.JPanel jpThongTinThanhToan;
    private javax.swing.JPanel jpThucDon;
    private javax.swing.JLabel lbGioDen;
    private javax.swing.JLabel lbTenBan;
    private javax.swing.JLabel lbTongTien;
    private javax.swing.JLabel lbTrangThai;
    // End of variables declaration//GEN-END:variables
}
