/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.QuanLy;

/**
 *
 * @author admin
 */
public class JpQuanLyMain extends javax.swing.JPanel {

    /**
     * Creates new form JpQuanLy
     */
    public JpQuanLyMain() {
        initComponents();
        LoadPanel(1);
    }
    JpQuanLyNhanVien qlnv;
    JpQuanLyBan ban;
    JpQuanLyMonAn td;
    JpQuanLyLoaiMonAn nm;
    JpQuanLyTaiKhoan nv;

    public void LoadPanel(int i) {
        jpql.removeAll();
        switch (i) {
            case 1:
                td = new JpQuanLyMonAn();
                jpql.add(td);
                break;
            case 2:
                ban = new JpQuanLyBan();
                jpql.add(ban);
                break;
            case 3:
                nm = new JpQuanLyLoaiMonAn();
                jpql.add(nm);
                break;
            case 4:
                nv = new JpQuanLyTaiKhoan();
                jpql.add(nv);
                break;
            case 5:
                qlnv = new JpQuanLyNhanVien();
                jpql.add(qlnv);
                break;
            default:
                break;
        }
        jpql.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnQuanLyMon = new javax.swing.JButton();
        btnQuanLyMonAn = new javax.swing.JButton();
        btnQuanLyBan = new javax.swing.JButton();
        btnQuanLytk = new javax.swing.JButton();
        btnQuanLyNV = new javax.swing.JButton();
        jpql = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(1051, 486));

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnQuanLyMon.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnQuanLyMon.setForeground(new java.awt.Color(51, 51, 0));
        btnQuanLyMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/kiemke.png"))); // NOI18N
        btnQuanLyMon.setText("QUẢN LÝ NHÓM MÓN");
        btnQuanLyMon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuanLyMon.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnQuanLyMon.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQuanLyMon.setIconTextGap(10);
        btnQuanLyMon.setPreferredSize(new java.awt.Dimension(0, 35));
        btnQuanLyMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyMonActionPerformed(evt);
            }
        });

        btnQuanLyMonAn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnQuanLyMonAn.setForeground(new java.awt.Color(51, 51, 0));
        btnQuanLyMonAn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/mailinglist.jpg"))); // NOI18N
        btnQuanLyMonAn.setText("QUẢN LÝ MÓN ĂN");
        btnQuanLyMonAn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuanLyMonAn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnQuanLyMonAn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQuanLyMonAn.setIconTextGap(10);
        btnQuanLyMonAn.setPreferredSize(new java.awt.Dimension(0, 35));
        btnQuanLyMonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyMonAnActionPerformed(evt);
            }
        });

        btnQuanLyBan.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnQuanLyBan.setForeground(new java.awt.Color(51, 51, 0));
        btnQuanLyBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/thucdon1.png"))); // NOI18N
        btnQuanLyBan.setText("QUẢN LÝ BÀN");
        btnQuanLyBan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuanLyBan.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnQuanLyBan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQuanLyBan.setIconTextGap(10);
        btnQuanLyBan.setPreferredSize(new java.awt.Dimension(0, 35));
        btnQuanLyBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyBanActionPerformed(evt);
            }
        });

        btnQuanLytk.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnQuanLytk.setForeground(new java.awt.Color(51, 51, 0));
        btnQuanLytk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/qluser.png"))); // NOI18N
        btnQuanLytk.setText("QUẢN LÝ TÀI KHOẢN");
        btnQuanLytk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuanLytk.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnQuanLytk.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQuanLytk.setIconTextGap(10);
        btnQuanLytk.setPreferredSize(new java.awt.Dimension(0, 35));
        btnQuanLytk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLytkActionPerformed(evt);
            }
        });

        btnQuanLyNV.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnQuanLyNV.setForeground(new java.awt.Color(51, 51, 0));
        btnQuanLyNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/qluser.png"))); // NOI18N
        btnQuanLyNV.setText("QUẢN LÝ NHÂN VIÊN");
        btnQuanLyNV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuanLyNV.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnQuanLyNV.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQuanLyNV.setIconTextGap(10);
        btnQuanLyNV.setPreferredSize(new java.awt.Dimension(0, 35));
        btnQuanLyNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyNVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuanLyMonAn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuanLyMon, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(btnQuanLyBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuanLytk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuanLyNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQuanLyMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuanLyMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuanLyBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuanLytk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuanLyNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpql.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpql, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpql, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuanLyMonAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyMonAnActionPerformed
        LoadPanel(1);// TODO add your handling code here:
    }//GEN-LAST:event_btnQuanLyMonAnActionPerformed

    private void btnQuanLyBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyBanActionPerformed
        LoadPanel(2);                // TODO add your handling code here:
    }//GEN-LAST:event_btnQuanLyBanActionPerformed

    private void btnQuanLyMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyMonActionPerformed
        LoadPanel(3);// TODO add your handling code here:
    }//GEN-LAST:event_btnQuanLyMonActionPerformed

    private void btnQuanLytkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLytkActionPerformed
        LoadPanel(4);  // TODO add your handling code here:
    }//GEN-LAST:event_btnQuanLytkActionPerformed

    private void btnQuanLyNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyNVActionPerformed
        // TODO add your handling code here:
        LoadPanel(5);
    }//GEN-LAST:event_btnQuanLyNVActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuanLyBan;
    private javax.swing.JButton btnQuanLyMon;
    private javax.swing.JButton btnQuanLyMonAn;
    private javax.swing.JButton btnQuanLyNV;
    private javax.swing.JButton btnQuanLytk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jpql;
    // End of variables declaration//GEN-END:variables
}
